### ISSUE TITLE
Understanding Environment Variables - Wiki Documentation

### ISSUE THREAD

**Issue by RyanRoberts210** [lux4rd0/kasa-collector#11]
Reading the Wiki in consecutive order; the Deploying Kasa Collector page shows four Optional environment variables.  The next page; Environment Flags, talks about only one of those four and ends with "For additional optional flags and explanations, please refer to the official documentation." which I am not sure where that is.  I assumed it was this Wiki...  Maybe a link?  A few pages later; How It Works, does have all four of those with explanations including a more detailed one that is also on the Environment Flags page.  I am not sure if these should be combined, or all added to the Environment Flags page with the deeper explanations on the How It Works page, etc...

**Comment by lux4rd0** [comment]
@RyanRoberts210 - I just moved the documentation off a single readme to the wiki to make finding content more accessible, but I omitted some details. I've updated the Environmental Flag Wiki page and included EVERYTHING available under the covers. Thanks for pointing out the gaps. It should be fixed now, and I made a custom sidebar that doesn't simply have alphabetized pages.
